import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css"
import PrelineScriptWrapper from '../components/PrelineScriptWrapper';
import { Navbar } from "@/components/index";
import { ReduxProvider } from "./providers";

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} antialiased max-w-3xl lg:max-w-5xl xl:max-w-[1930px] m-auto`} cz-shortcut-listen="true">
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
